### ISSUE TITLE
Can't run the example from the README

### ISSUE THREAD

**Issue by jpleau** [Olivine-Labs/say#10]
Hello !

(Currently packaging for Debian a few of your libraries leading up to busted !). I've encountered a little issue when testing the installed package. The example in the README.md for say doesn't work (Tested with lua 5.1 and 5.2):

```
lua5.1: /usr/share/lua/5.1/say/init.lua:44: bad argument #1 to 'ipairs' (table expected, got number)
stack traceback:
    [C]: in function 'ipairs'
    /usr/share/lua/5.1/say/init.lua:44: in function 's'
    z.lua:8: in main chunk
    [C]: ?

```

Changing 

```
print(s('money', 1000)) -- I have 1000 dollars
```

to

```
print(s('money', {1000})) -- I have 1000 dollars
```

in README.md makes it work. Should this be fixed in the readme or in the library so that it builds a one element table if passed a string/number ?

Cheers

**Comment by DorianGray** [comment]
Probably in the library, not that this is probably relevant 5 years post :/ Sorry about that, most likely directly my fault.
